[book]
authors = ["Moein Halvaei"]
language = "en"
multilingual = true
src = "src"
title = "jobname"

# [preprocessor.mermaid]
# command = "mdbook-mermaid"

# [output.html]
# additional-js = ["mermaid.min.js", "mermaid-init.js"]
